### ISSUE TITLE
when create ramdisk will error，how can slove it

### ISSUE THREAD

**Issue by striveben** [netsirkl64/palera1n-High-Sierra#1]
<img width="813" alt="image" src="https://user-images.githubusercontent.com/61238912/204132797-fc4f6560-d87d-49b7-87d5-7591dcb7bfc2.png">

but,when i create active ,it will display "Read-only file system"
<img width="375" alt="image" src="https://user-images.githubusercontent.com/61238912/204132821-21a52451-76ff-4157-a768-83b03eda8055.png">

My devices is iphone 7 plus , IOS version is 15.6.1.

Please help ,thanks.

**Comment by ghost** [comment]
this has been fixed in the latest commit, thank you

**Comment by striveben** [comment]
thanks
I try the new code ,but it still display the same mistakes.
Please help

**Comment by ghost** [comment]
you need to delete your palera1n folder and do a fresh clone
