### ISSUE TITLE
No Package manager slection

### ISSUE THREAD

**Issue by tornado207** [netsirkl64/palera1n-High-Sierra#12]
I used the new GUI to jailbreak my IPAD and after finding Palera1n app on home screen i opened it and when i press the gear to select the package manager i find nothing there except the tools. i jailbroke the IPAD and i got a jailbroken device with sileo as default installed.

I see that i should have the ability to install another package like cydia but the Palera1n app i got not containing this option.

**Info (please complete the following information):**
- iDevice's version: [iOS 16.1]
- Computer OS and version: [Monterey. macOS 12.6.2]
- The command you ran: [Palera1n GUI]
![IMG_0001](https://user-images.githubusercontent.com/110396994/210015164-6b6d024c-d1cd-4a2a-aa23-f5d77f5962a7.PNG)

**Comment by ghost** [comment]
cydia and zebra can be installed from the pre included repos that come on sileo using this fork of palera1n

installing other package managers in palera1n app on this fork of palera1n is unsupported and never will be supported
